# Generated by Django 4.1 on 2022-09-06 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatroom", old_name="id", new_name="room_id",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="creation_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Creation Date"
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="language",
            field=models.CharField(
                choices=[
                    ("EN", "English"),
                    ("FR", "French"),
                    ("ES", "Spanish"),
                    ("ZH", "Chinese"),
                    ("JA", "Japanese"),
                ],
                default="English",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="num_member",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
